apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev  

commonLabels:
  stack: backend
commonAnnotations:
  apponwer: poc_guy 
  appnature: print_env

resources:
 - namespace.yaml
 - ../../../app/base/

patchesStrategicMerge:
- deployment_app.yaml
- replica-and-rollout-strategy.yaml

images:
- name: iamraj007/printenv:output
  newTag: output

nameSuffix: -dev
namePrefix: backend-
